### ISSUE TITLE
证书存在问题

### ISSUE THREAD

**Issue by tgllsy** [XRSec/AWVS14-Docker#1]
无法扫描，显示证书已达到授权限制。
![iShot2021-10-07 03 32 25](https://user-images.githubusercontent.com/19581396/136270938-883271aa-1923-4143-8d65-e5dc153904af.png)

**Comment by Ran-Xing** [comment]
@tgllsy 我测试一下，这个应该是破解的问题，容器还在吗？可以远程调试吗？我看下为啥错误

**Comment by Ran-Xing** [comment]
已经搞定了
