### ISSUE TITLE
How to Install AWVS14-Docker

### ISSUE THREAD

**Issue by secfb** [XRSec/AWVS14-Docker#2]
Hi,
Dude how exactly is acunetix installed. I am using mac with m1 processor. I installed docker on Kali linux arm64. How do we install from the commands below. Can you help with this? I really couldn't install. how to run docker especially for arm64. Can you make a video on this topic. I really tried everything but failed.
After successful installation, we will call acunetix via which ip address. docker0,eth0 and lo ? You have prepared a really nice repo but it is not fully understood.

------------

```bash
git clone https://github.com/XRSec/AWVS14-Docker.git
```
```ruby
docker pull xrsec/awvs
```
```powehsell
docker run -it -d --name awvs -p 3443:3443 xrsec/awvs:latest
```
--------------
I get the following error.
`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

**Comment by Ran-Xing** [comment]
Hey, man, now.AcunetixThe company did not provide the arm software package.

**Comment by secfb** [comment]
Actually, docker m1 is desked on computers. Even if the operating system is arm64, is it not possible to install arm64 as a docker image?I wanted to ask you because I don't know about this.

**Comment by Ran-Xing** [comment]
The package only supports systems with the AMD64 architecture, so it cannot be installed on ARM64 M1

**Comment by Ran-Xing** [comment]
![image](https://user-images.githubusercontent.com/73819467/137478657-7d3a9d52-c6b0-4cc8-ab61-18bcbd0d473f.png)
@secfb

**Comment by Ran-Xing** [comment]
@secfb https://github.com/XRSec/Mac_M1_Docker
Here is a list of warehouses dedicated to providing adaptations for M1, I hope you'll like it
